[package]
name = "<SET_PACKAGE_NAME>"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.txt"
authors = ["SarahGreyWolf <m.sarahgreywolf@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
