#[derive(Debug)]
pub enum Mnemonic {
    Aaload,
    Aastore,
    AconstNull,
    Aload,
    Aload0,
    Aload1,
    Aload2,
    Aload3,
    Anewarray,
    Areturn,
    Arraylength,
    Astore,
    Astore0,
    Astore1,
    Astore2,
    Astore3,
    Athrow,
    Baload,
    Bastore,
    Bipush,
    Caload,
    Castore,
    Checkcast,
    D2f,
    D2i,
    D2l,
    Dadd,
    Daload,
    Dastore,
    Dcmpg,
    Dcmpl,
    Dconst0,
    Dconst1,
    Ddiv,
    Dload,
    Dload0,
    Dload1,
    Dload2,
    Dload3,
    Dmul,
    Dneg,
    Drem,
    Dreturn,
    Dstore,
    Dstore0,
    Dstore1,
    Dstore2,
    Dstore3,
    Dsub,
    Dup,
    DupX1,
    DupX2,
    Dup2,
    Dup2X1,
    Dup2X2,
    F2d,
    F2i,
    F2l,
    Fadd,
    Faload,
    Fastore,
    Fcmpg,
    Fcmpl,
    Fconst0,
    Fconst1,
    Fconst2,
    Fdiv,
    Fload,
    Fload0,
    Fload1,
    Fload2,
    Fload3,
    Fmul,
    Fneg,
    Frem,
    Freturn,
    Fstore,
    Fstore0,
    Fstore1,
    Fstore2,
    Fstore3,
    Fsub,
    Getfield,
    Getstatic,
    Goto,
    GotoW,
    I2b,
    I2c,
    I2d,
    I2f,
    I2l,
    I2s,
    Iadd,
    Iaload,
    Iand,
    Iastore,
    IconstM1,
    Iconst0,
    Iconst1,
    Iconst2,
    Iconst3,
    Iconst4,
    Iconst5,
    Idiv,
    IfAcmpeq,
    IfAcmpne,
    IfIcmpeq,
    IfIcmpne,
    IfIcmplt,
    IfIcmpge,
    IfIcmpgt,
    IfIcmple,
    Ifeq,
    Ifne,
    Iflt,
    Ifge,
    Ifgt,
    Ifle,
    Ifnonnull,
    Ifnull,
    Iinc,
    Iload,
    Iload0,
    Iload1,
    Iload2,
    Iload3,
    Imul,
    Ineg,
    Instanceof,
    Invokedynamic,
    Invokeinterface,
    Invokespecial,
    Invokestatic,
    Invokevirtual,
    Ior,
    Irem,
    Ireturn,
    Ishl,
    Ishr,
    Istore,
    Istore0,
    Istore1,
    Istore2,
    Istore3,
    Isub,
    Iushr,
    Ixor,
    Jsr,
    JsrW,
    L2d,
    L2f,
    L2i,
    Ladd,
    Laload,
    Land,
    Lastore,
    Lcmp,
    Lconst0,
    Lconst1,
    Ldc,
    LdcW,
    Ldc2W,
    Ldiv,
    Lload,
    Lload0,
    Lload1,
    Lload2,
    Lload3,
    Lmul,
    Lneg,
    Lookupswitch,
    Lor,
    Lrem,
    Lreturn,
    Lshl,
    Lshr,
    Lstore,
    Lstore0,
    Lstore1,
    Lstore2,
    Lstore3,
    Lsub,
    Lushr,
    Lxor,
    Monitorenter,
    Monitorexit,
    Multianewarray,
    New,
    Newarray,
    Nop,
    Pop,
    Pop2,
    Putfield,
    Putstatic,
    Ret,
    Return,
    Saload,
    Satore,
    Sipush,
    Swap,
    Tableswitch,
    WideOp,
    WideIinc,
    Unknown(u8),
}

impl From<Mnemonic> for String {
    fn from(value: Mnemonic) -> Self {
        match value {
            Mnemonic::Aaload => "aaload",
            Mnemonic::Aastore => "aastore",
            Mnemonic::AconstNull => "aconst_null",
            Mnemonic::Aload => "aload",
            Mnemonic::Aload0 => "aload_0",
            Mnemonic::Aload1 => "aload_1",
            Mnemonic::Aload2 => "aload_2",
            Mnemonic::Aload3 => "aload_3",
            Mnemonic::Anewarray => "anewarray",
            Mnemonic::Areturn => "areturn",
            Mnemonic::Arraylength => "arraylength",
            Mnemonic::Astore => "astore",
            Mnemonic::Astore0 => "astore_0",
            Mnemonic::Astore1 => "astore_1",
            Mnemonic::Astore2 => "astore_2",
            Mnemonic::Astore3 => "astore_3",
            Mnemonic::Athrow => "athrow",
            Mnemonic::Baload => "baload",
            Mnemonic::Bastore => "bastore",
            Mnemonic::Bipush => "bipush",
            Mnemonic::Caload => "caload",
            Mnemonic::Castore => "castore",
            Mnemonic::Checkcast => "checkcast",
            Mnemonic::D2f => "d2f",
            Mnemonic::D2i => "d2i",
            Mnemonic::D2l => "d2l",
            Mnemonic::Dadd => "dadd",
            Mnemonic::Daload => "daload",
            Mnemonic::Dastore => "dastore",
            Mnemonic::Dcmpg => "dcmpg",
            Mnemonic::Dcmpl => "dcmpl",
            Mnemonic::Dconst0 => "dconst_0",
            Mnemonic::Dconst1 => "dconst_1",
            Mnemonic::Ddiv => "ddiv",
            Mnemonic::Dload => "dload",
            Mnemonic::Dload0 => "dload_0",
            Mnemonic::Dload1 => "dload_1",
            Mnemonic::Dload2 => "dload_2",
            Mnemonic::Dload3 => "dload_3",
            Mnemonic::Dmul => "dmul",
            Mnemonic::Dneg => "dneg",
            Mnemonic::Drem => "drem",
            Mnemonic::Dreturn => "dreturn",
            Mnemonic::Dstore => "dstore",
            Mnemonic::Dstore0 => "dstore_0",
            Mnemonic::Dstore1 => "dstore_1",
            Mnemonic::Dstore2 => "dstore_2",
            Mnemonic::Dstore3 => "dstore_3",
            Mnemonic::Dsub => "dsub",
            Mnemonic::Dup => "dup",
            Mnemonic::DupX1 => "dup_x1",
            Mnemonic::DupX2 => "dup_x2",
            Mnemonic::Dup2 => "dup2",
            Mnemonic::Dup2X1 => "dup2_x1",
            Mnemonic::Dup2X2 => "dup2_x2",
            Mnemonic::F2d => "f2d",
            Mnemonic::F2i => "f2i",
            Mnemonic::F2l => "f2l",
            Mnemonic::Fadd => "fadd",
            Mnemonic::Faload => "faload",
            Mnemonic::Fastore => "fastore",
            Mnemonic::Fcmpg => "fcmpg",
            Mnemonic::Fcmpl => "fcmpl",
            Mnemonic::Fconst0 => "fconst_0",
            Mnemonic::Fconst1 => "fconst_1",
            Mnemonic::Fconst2 => "fconst_2",
            Mnemonic::Fdiv => "fdiv",
            Mnemonic::Fload => "fload",
            Mnemonic::Fload0 => "fload_0",
            Mnemonic::Fload1 => "fload_1",
            Mnemonic::Fload2 => "fload_2",
            Mnemonic::Fload3 => "fload_3",
            Mnemonic::Fmul => "fmul",
            Mnemonic::Fneg => "fneg",
            Mnemonic::Frem => "frem",
            Mnemonic::Freturn => "freturn",
            Mnemonic::Fstore => "fstore",
            Mnemonic::Fstore0 => "fstore_0",
            Mnemonic::Fstore1 => "fstore_1",
            Mnemonic::Fstore2 => "fstore_2",
            Mnemonic::Fstore3 => "fstore_3",
            Mnemonic::Fsub => "fsub",
            Mnemonic::Getfield => "getfield",
            Mnemonic::Getstatic => "getstatic",
            Mnemonic::Goto => "goto",
            Mnemonic::GotoW => "goto_w",
            Mnemonic::I2b => "i2b",
            Mnemonic::I2c => "i2c",
            Mnemonic::I2d => "i2d",
            Mnemonic::I2f => "i2f",
            Mnemonic::I2l => "i2l",
            Mnemonic::I2s => "i2s",
            Mnemonic::Iadd => "iadd",
            Mnemonic::Iaload => "iaload",
            Mnemonic::Iand => "iand",
            Mnemonic::Iastore => "iastore",
            Mnemonic::IconstM1 => "iconst_m1",
            Mnemonic::Iconst0 => "iconst_0",
            Mnemonic::Iconst1 => "iconst_1",
            Mnemonic::Iconst2 => "iconst_2",
            Mnemonic::Iconst3 => "iconst_3",
            Mnemonic::Iconst4 => "iconst_4",
            Mnemonic::Iconst5 => "iconst_5",
            Mnemonic::Idiv => "idiv",
            Mnemonic::IfAcmpeq => "if_acmpeq",
            Mnemonic::IfAcmpne => "if_acmpne",
            Mnemonic::IfIcmpeq => "if_icmpeq",
            Mnemonic::IfIcmpne => "if_icmpne",
            Mnemonic::IfIcmplt => "if_icmplt",
            Mnemonic::IfIcmpge => "if_icmpge",
            Mnemonic::IfIcmpgt => "if_icmpgt",
            Mnemonic::IfIcmple => "if_icmple",
            Mnemonic::Ifeq => "ifeq",
            Mnemonic::Ifne => "ifne",
            Mnemonic::Iflt => "iflt",
            Mnemonic::Ifge => "ifge",
            Mnemonic::Ifgt => "ifgt",
            Mnemonic::Ifle => "ifle",
            Mnemonic::Ifnonnull => "ifnonnull",
            Mnemonic::Ifnull => "ifnull",
            Mnemonic::Iinc => "iinc",
            Mnemonic::Iload => "iload",
            Mnemonic::Iload0 => "iload_0",
            Mnemonic::Iload1 => "iload_1",
            Mnemonic::Iload2 => "iload_2",
            Mnemonic::Iload3 => "iload_3",
            Mnemonic::Imul => "imul",
            Mnemonic::Ineg => "ineg",
            Mnemonic::Instanceof => "instanceof",
            Mnemonic::Invokedynamic => "invokedynamic",
            Mnemonic::Invokeinterface => "invokeinterface",
            Mnemonic::Invokespecial => "invokespecial",
            Mnemonic::Invokestatic => "invokestatic",
            Mnemonic::Invokevirtual => "invokevirtual",
            Mnemonic::Ior => "ior",
            Mnemonic::Irem => "irem",
            Mnemonic::Ireturn => "ireturn",
            Mnemonic::Ishl => "ishl",
            Mnemonic::Ishr => "ishr",
            Mnemonic::Istore => "istore",
            Mnemonic::Istore0 => "istore_0",
            Mnemonic::Istore1 => "istore_1",
            Mnemonic::Istore2 => "istore_2",
            Mnemonic::Istore3 => "istore_3",
            Mnemonic::Isub => "isub",
            Mnemonic::Iushr => "iushr",
            Mnemonic::Ixor => "ixor",
            Mnemonic::Jsr => "jsr",
            Mnemonic::JsrW => "jsr_w",
            Mnemonic::L2d => "l2d",
            Mnemonic::L2f => "l2f",
            Mnemonic::L2i => "l2i",
            Mnemonic::Ladd => "ladd",
            Mnemonic::Laload => "laload",
            Mnemonic::Land => "land",
            Mnemonic::Lastore => "lastore",
            Mnemonic::Lcmp => "lcmp",
            Mnemonic::Lconst0 => "lconst_0",
            Mnemonic::Lconst1 => "lconst_1",
            Mnemonic::Ldc => "ldc",
            Mnemonic::LdcW => "ldc_w",
            Mnemonic::Ldc2W => "ldc2_w",
            Mnemonic::Ldiv => "ldiv",
            Mnemonic::Lload => "lload",
            Mnemonic::Lload0 => "lload_0",
            Mnemonic::Lload1 => "lload_1",
            Mnemonic::Lload2 => "lload_2",
            Mnemonic::Lload3 => "lload_3",
            Mnemonic::Lmul => "lmul",
            Mnemonic::Lneg => "lneg",
            Mnemonic::Lookupswitch => "lookupswitch",
            Mnemonic::Lor => "lor",
            Mnemonic::Lrem => "lrem",
            Mnemonic::Lreturn => "lreturn",
            Mnemonic::Lshl => "lshl",
            Mnemonic::Lshr => "lshr",
            Mnemonic::Lstore => "lstore",
            Mnemonic::Lstore0 => "lstore_0",
            Mnemonic::Lstore1 => "lstore_1",
            Mnemonic::Lstore2 => "lstore_2",
            Mnemonic::Lstore3 => "lstore_3",
            Mnemonic::Lsub => "lsub",
            Mnemonic::Lushr => "lushr",
            Mnemonic::Lxor => "lxor",
            Mnemonic::Monitorenter => "monitorenter",
            Mnemonic::Monitorexit => "monitorexit",
            Mnemonic::Multianewarray => "multianewarray",
            Mnemonic::New => "new",
            Mnemonic::Newarray => "newarray",
            Mnemonic::Nop => "nop",
            Mnemonic::Pop => "pop",
            Mnemonic::Pop2 => "pop2",
            Mnemonic::Putfield => "putfield",
            Mnemonic::Putstatic => "putstatic",
            Mnemonic::Ret => "ret",
            Mnemonic::Return => "return",
            Mnemonic::Saload => "saload",
            Mnemonic::Satore => "satore",
            Mnemonic::Sipush => "sipush",
            Mnemonic::Swap => "swap",
            Mnemonic::Tableswitch => "tableswitch",
            Mnemonic::WideOp => "wide",
            Mnemonic::WideIinc => "wide",
            Mnemonic::Unknown(_) => "UNKNOWN",
        }
        .into()
    }
}

impl From<Mnemonic> for u8 {
    fn from(value: Mnemonic) -> Self {
        match value {
            Mnemonic::Aaload => 0x32,
            Mnemonic::Aastore => 0x53,
            Mnemonic::AconstNull => 0x01,
            Mnemonic::Aload => 0x19,
            Mnemonic::Aload0 => 0x2a,
            Mnemonic::Aload1 => 0x2b,
            Mnemonic::Aload2 => 0x2c,
            Mnemonic::Aload3 => 0x2d,
            Mnemonic::Anewarray => 0xbd,
            Mnemonic::Areturn => 0xb0,
            Mnemonic::Arraylength => 0xbe,
            Mnemonic::Astore => 0x3a,
            Mnemonic::Astore0 => 0x4b,
            Mnemonic::Astore1 => 0x4c,
            Mnemonic::Astore2 => 0x4d,
            Mnemonic::Astore3 => 0x4e,
            Mnemonic::Athrow => 0xbf,
            Mnemonic::Baload => 0x33,
            Mnemonic::Bastore => 0x54,
            Mnemonic::Bipush => 0x10,
            Mnemonic::Caload => 0x34,
            Mnemonic::Castore => 0x55,
            Mnemonic::Checkcast => 0xc0,
            Mnemonic::D2f => 0x90,
            Mnemonic::D2i => 0x8e,
            Mnemonic::D2l => 0x8f,
            Mnemonic::Dadd => 0x63,
            Mnemonic::Daload => 0x31,
            Mnemonic::Dastore => 0x52,
            Mnemonic::Dcmpg => 0x98,
            Mnemonic::Dcmpl => 0x97,
            Mnemonic::Dconst0 => 0x0e,
            Mnemonic::Dconst1 => 0x0f,
            Mnemonic::Ddiv => 0x6f,
            Mnemonic::Dload => 0x18,
            Mnemonic::Dload0 => 0x26,
            Mnemonic::Dload1 => 0x27,
            Mnemonic::Dload2 => 0x28,
            Mnemonic::Dload3 => 0x29,
            Mnemonic::Dmul => 0x6b,
            Mnemonic::Dneg => 0x77,
            Mnemonic::Drem => 0x73,
            Mnemonic::Dreturn => 0xaf,
            Mnemonic::Dstore => 0x39,
            Mnemonic::Dstore0 => 0x47,
            Mnemonic::Dstore1 => 0x48,
            Mnemonic::Dstore2 => 0x49,
            Mnemonic::Dstore3 => 0x4a,
            Mnemonic::Dsub => 0x67,
            Mnemonic::Dup => 0x59,
            Mnemonic::DupX1 => 0x5a,
            Mnemonic::DupX2 => 0x5b,
            Mnemonic::Dup2 => 0x5c,
            Mnemonic::Dup2X1 => 0x5d,
            Mnemonic::Dup2X2 => 0x5e,
            Mnemonic::F2d => 0x8d,
            Mnemonic::F2i => 0x8b,
            Mnemonic::F2l => 0x8c,
            Mnemonic::Fadd => 0x62,
            Mnemonic::Faload => 0x30,
            Mnemonic::Fastore => 0x51,
            Mnemonic::Fcmpg => 0x96,
            Mnemonic::Fcmpl => 0x95,
            Mnemonic::Fconst0 => 0x0b,
            Mnemonic::Fconst1 => 0x0c,
            Mnemonic::Fconst2 => 0x0d,
            Mnemonic::Fdiv => 0x6e,
            Mnemonic::Fload => 0x17,
            Mnemonic::Fload0 => 0x22,
            Mnemonic::Fload1 => 0x23,
            Mnemonic::Fload2 => 0x24,
            Mnemonic::Fload3 => 0x25,
            Mnemonic::Fmul => 0x6a,
            Mnemonic::Fneg => 0x76,
            Mnemonic::Frem => 0x72,
            Mnemonic::Freturn => 0xae,
            Mnemonic::Fstore => 0x38,
            Mnemonic::Fstore0 => 0x43,
            Mnemonic::Fstore1 => 0x44,
            Mnemonic::Fstore2 => 0x45,
            Mnemonic::Fstore3 => 0x46,
            Mnemonic::Fsub => 0x66,
            Mnemonic::Getfield => 0xb4,
            Mnemonic::Getstatic => 0xb2,
            Mnemonic::Goto => 0xa7,
            Mnemonic::GotoW => 0xc8,
            Mnemonic::I2b => 0x91,
            Mnemonic::I2c => 0x92,
            Mnemonic::I2d => 0x87,
            Mnemonic::I2f => 0x86,
            Mnemonic::I2l => 0x85,
            Mnemonic::I2s => 0x93,
            Mnemonic::Iadd => 0x60,
            Mnemonic::Iaload => 0x2e,
            Mnemonic::Iand => 0x7e,
            Mnemonic::Iastore => 0x4f,
            Mnemonic::IconstM1 => 0x02,
            Mnemonic::Iconst0 => 0x03,
            Mnemonic::Iconst1 => 0x04,
            Mnemonic::Iconst2 => 0x05,
            Mnemonic::Iconst3 => 0x06,
            Mnemonic::Iconst4 => 0x07,
            Mnemonic::Iconst5 => 0x08,
            Mnemonic::Idiv => 0x6c,
            Mnemonic::IfAcmpeq => 0xa5,
            Mnemonic::IfAcmpne => 0xa6,
            Mnemonic::IfIcmpeq => 0x9f,
            Mnemonic::IfIcmpne => 0xa0,
            Mnemonic::IfIcmplt => 0xa1,
            Mnemonic::IfIcmpge => 0xa2,
            Mnemonic::IfIcmpgt => 0xa3,
            Mnemonic::IfIcmple => 0xa4,
            Mnemonic::Ifeq => 0x99,
            Mnemonic::Ifne => 0x9a,
            Mnemonic::Iflt => 0x9b,
            Mnemonic::Ifge => 0x9c,
            Mnemonic::Ifgt => 0x9d,
            Mnemonic::Ifle => 0x9e,
            Mnemonic::Ifnonnull => 0xc7,
            Mnemonic::Ifnull => 0xc6,
            Mnemonic::Iinc => 0x84,
            Mnemonic::Iload => 0x15,
            Mnemonic::Iload0 => 0x1a,
            Mnemonic::Iload1 => 0x1b,
            Mnemonic::Iload2 => 0x1c,
            Mnemonic::Iload3 => 0x1d,
            Mnemonic::Imul => 0x68,
            Mnemonic::Ineg => 0x74,
            Mnemonic::Instanceof => 0xc1,
            Mnemonic::Invokedynamic => 0xba,
            Mnemonic::Invokeinterface => 0xb9,
            Mnemonic::Invokespecial => 0xb7,
            Mnemonic::Invokestatic => 0xb8,
            Mnemonic::Invokevirtual => 0xb6,
            Mnemonic::Ior => 0x80,
            Mnemonic::Irem => 0x70,
            Mnemonic::Ireturn => 0xac,
            Mnemonic::Ishl => 0x78,
            Mnemonic::Ishr => 0x7a,
            Mnemonic::Istore => 0x36,
            Mnemonic::Istore0 => 0x3b,
            Mnemonic::Istore1 => 0x3c,
            Mnemonic::Istore2 => 0x3d,
            Mnemonic::Istore3 => 0x3e,
            Mnemonic::Isub => 0x64,
            Mnemonic::Iushr => 0x7c,
            Mnemonic::Ixor => 0x82,
            Mnemonic::Jsr => 0xa8,
            Mnemonic::JsrW => 0xc9,
            Mnemonic::L2d => 0x8a,
            Mnemonic::L2f => 0x89,
            Mnemonic::L2i => 0x88,
            Mnemonic::Ladd => 0x61,
            Mnemonic::Laload => 0x2f,
            Mnemonic::Land => 0x7f,
            Mnemonic::Lastore => 0x50,
            Mnemonic::Lcmp => 0x94,
            Mnemonic::Lconst0 => 0x09,
            Mnemonic::Lconst1 => 0x0a,
            Mnemonic::Ldc => 0x12,
            Mnemonic::LdcW => 0x13,
            Mnemonic::Ldc2W => 0x14,
            Mnemonic::Ldiv => 0x6d,
            Mnemonic::Lload => 0x16,
            Mnemonic::Lload0 => 0x1e,
            Mnemonic::Lload1 => 0x1f,
            Mnemonic::Lload2 => 0x20,
            Mnemonic::Lload3 => 0x21,
            Mnemonic::Lmul => 0x69,
            Mnemonic::Lneg => 0x75,
            Mnemonic::Lookupswitch => 0xab,
            Mnemonic::Lor => 0x81,
            Mnemonic::Lrem => 0x71,
            Mnemonic::Lreturn => 0xad,
            Mnemonic::Lshl => 0x79,
            Mnemonic::Lshr => 0x7b,
            Mnemonic::Lstore => 0x37,
            Mnemonic::Lstore0 => 0x3f,
            Mnemonic::Lstore1 => 0x40,
            Mnemonic::Lstore2 => 0x41,
            Mnemonic::Lstore3 => 0x42,
            Mnemonic::Lsub => 0x65,
            Mnemonic::Lushr => 0x7d,
            Mnemonic::Lxor => 0x83,
            Mnemonic::Monitorenter => 0xc2,
            Mnemonic::Monitorexit => 0xc3,
            Mnemonic::Multianewarray => 0xc5,
            Mnemonic::New => 0xbb,
            Mnemonic::Newarray => 0xbc,
            Mnemonic::Nop => 0x00,
            Mnemonic::Pop => 0x57,
            Mnemonic::Pop2 => 0x58,
            Mnemonic::Putfield => 0xb5,
            Mnemonic::Putstatic => 0xb3,
            Mnemonic::Ret => 0xa9,
            Mnemonic::Return => 0xb1,
            Mnemonic::Saload => 0x35,
            Mnemonic::Satore => 0x56,
            Mnemonic::Sipush => 0x11,
            Mnemonic::Swap => 0x5f,
            Mnemonic::Tableswitch => 0xaa,
            Mnemonic::WideOp => 0xc4,
            Mnemonic::WideIinc => 0xc4,
            Mnemonic::Unknown(opcode) => 0x00,
        }
    }
}

impl From<u8> for Mnemonic {
    fn from(value: u8) -> Self {
        match value {
            0x32 => Mnemonic::Aaload,
            0x53 => Mnemonic::Aastore,
            0x01 => Mnemonic::AconstNull,
            0x19 => Mnemonic::Aload,
            0x2a => Mnemonic::Aload0,
            0x2b => Mnemonic::Aload1,
            0x2c => Mnemonic::Aload2,
            0x2d => Mnemonic::Aload3,
            0xbd => Mnemonic::Anewarray,
            0xb0 => Mnemonic::Areturn,
            0xbe => Mnemonic::Arraylength,
            0x3a => Mnemonic::Astore,
            0x4b => Mnemonic::Astore0,
            0x4c => Mnemonic::Astore1,
            0x4d => Mnemonic::Astore2,
            0x4e => Mnemonic::Astore3,
            0xbf => Mnemonic::Athrow,
            0x33 => Mnemonic::Baload,
            0x54 => Mnemonic::Bastore,
            0x10 => Mnemonic::Bipush,
            0x34 => Mnemonic::Caload,
            0x55 => Mnemonic::Castore,
            0xc0 => Mnemonic::Checkcast,
            0x90 => Mnemonic::D2f,
            0x8e => Mnemonic::D2i,
            0x8f => Mnemonic::D2l,
            0x63 => Mnemonic::Dadd,
            0x31 => Mnemonic::Daload,
            0x52 => Mnemonic::Dastore,
            0x98 => Mnemonic::Dcmpg,
            0x97 => Mnemonic::Dcmpl,
            0x0e => Mnemonic::Dconst0,
            0x0f => Mnemonic::Dconst1,
            0x6f => Mnemonic::Ddiv,
            0x18 => Mnemonic::Dload,
            0x26 => Mnemonic::Dload0,
            0x27 => Mnemonic::Dload1,
            0x28 => Mnemonic::Dload2,
            0x29 => Mnemonic::Dload3,
            0x6b => Mnemonic::Dmul,
            0x77 => Mnemonic::Dneg,
            0x73 => Mnemonic::Drem,
            0xaf => Mnemonic::Dreturn,
            0x39 => Mnemonic::Dstore,
            0x47 => Mnemonic::Dstore0,
            0x48 => Mnemonic::Dstore1,
            0x49 => Mnemonic::Dstore2,
            0x4a => Mnemonic::Dstore3,
            0x67 => Mnemonic::Dsub,
            0x59 => Mnemonic::Dup,
            0x5a => Mnemonic::DupX1,
            0x5b => Mnemonic::DupX2,
            0x5c => Mnemonic::Dup2,
            0x5d => Mnemonic::Dup2X1,
            0x5e => Mnemonic::Dup2X2,
            0x8d => Mnemonic::F2d,
            0x8b => Mnemonic::F2i,
            0x8c => Mnemonic::F2l,
            0x62 => Mnemonic::Fadd,
            0x30 => Mnemonic::Faload,
            0x51 => Mnemonic::Fastore,
            0x96 => Mnemonic::Fcmpg,
            0x95 => Mnemonic::Fcmpl,
            0x0b => Mnemonic::Fconst0,
            0x0c => Mnemonic::Fconst1,
            0x0d => Mnemonic::Fconst2,
            0x6e => Mnemonic::Fdiv,
            0x17 => Mnemonic::Fload,
            0x22 => Mnemonic::Fload0,
            0x23 => Mnemonic::Fload1,
            0x24 => Mnemonic::Fload2,
            0x25 => Mnemonic::Fload3,
            0x6a => Mnemonic::Fmul,
            0x76 => Mnemonic::Fneg,
            0x72 => Mnemonic::Frem,
            0xae => Mnemonic::Freturn,
            0x38 => Mnemonic::Fstore,
            0x43 => Mnemonic::Fstore0,
            0x44 => Mnemonic::Fstore1,
            0x45 => Mnemonic::Fstore2,
            0x46 => Mnemonic::Fstore3,
            0x66 => Mnemonic::Fsub,
            0xb4 => Mnemonic::Getfield,
            0xb2 => Mnemonic::Getstatic,
            0xa7 => Mnemonic::Goto,
            0xc8 => Mnemonic::GotoW,
            0x91 => Mnemonic::I2b,
            0x92 => Mnemonic::I2c,
            0x87 => Mnemonic::I2d,
            0x86 => Mnemonic::I2f,
            0x85 => Mnemonic::I2l,
            0x93 => Mnemonic::I2s,
            0x60 => Mnemonic::Iadd,
            0x2e => Mnemonic::Iaload,
            0x7e => Mnemonic::Iand,
            0x4f => Mnemonic::Iastore,
            0x02 => Mnemonic::IconstM1,
            0x03 => Mnemonic::Iconst0,
            0x04 => Mnemonic::Iconst1,
            0x05 => Mnemonic::Iconst2,
            0x06 => Mnemonic::Iconst3,
            0x07 => Mnemonic::Iconst4,
            0x08 => Mnemonic::Iconst5,
            0x6c => Mnemonic::Idiv,
            0xa5 => Mnemonic::IfAcmpeq,
            0xa6 => Mnemonic::IfAcmpne,
            0x9f => Mnemonic::IfIcmpeq,
            0xa0 => Mnemonic::IfIcmpne,
            0xa1 => Mnemonic::IfIcmplt,
            0xa2 => Mnemonic::IfIcmpge,
            0xa3 => Mnemonic::IfIcmpgt,
            0xa4 => Mnemonic::IfIcmple,
            0x99 => Mnemonic::Ifeq,
            0x9a => Mnemonic::Ifne,
            0x9b => Mnemonic::Iflt,
            0x9c => Mnemonic::Ifge,
            0x9d => Mnemonic::Ifgt,
            0x9e => Mnemonic::Ifle,
            0xc7 => Mnemonic::Ifnonnull,
            0xc6 => Mnemonic::Ifnull,
            0x84 => Mnemonic::Iinc,
            0x15 => Mnemonic::Iload,
            0x1a => Mnemonic::Iload0,
            0x1b => Mnemonic::Iload1,
            0x1c => Mnemonic::Iload2,
            0x1d => Mnemonic::Iload3,
            0x68 => Mnemonic::Imul,
            0x74 => Mnemonic::Ineg,
            0xc1 => Mnemonic::Instanceof,
            0xba => Mnemonic::Invokedynamic,
            0xb9 => Mnemonic::Invokeinterface,
            0xb7 => Mnemonic::Invokespecial,
            0xb8 => Mnemonic::Invokestatic,
            0xb6 => Mnemonic::Invokevirtual,
            0x80 => Mnemonic::Ior,
            0x70 => Mnemonic::Irem,
            0xac => Mnemonic::Ireturn,
            0x78 => Mnemonic::Ishl,
            0x7a => Mnemonic::Ishr,
            0x36 => Mnemonic::Istore,
            0x3b => Mnemonic::Istore0,
            0x3c => Mnemonic::Istore1,
            0x3d => Mnemonic::Istore2,
            0x3e => Mnemonic::Istore3,
            0x64 => Mnemonic::Isub,
            0x7c => Mnemonic::Iushr,
            0x82 => Mnemonic::Ixor,
            0xa8 => Mnemonic::Jsr,
            0xc9 => Mnemonic::JsrW,
            0x8a => Mnemonic::L2d,
            0x89 => Mnemonic::L2f,
            0x88 => Mnemonic::L2i,
            0x61 => Mnemonic::Ladd,
            0x2f => Mnemonic::Laload,
            0x7f => Mnemonic::Land,
            0x50 => Mnemonic::Lastore,
            0x94 => Mnemonic::Lcmp,
            0x09 => Mnemonic::Lconst0,
            0x0a => Mnemonic::Lconst1,
            0x12 => Mnemonic::Ldc,
            0x13 => Mnemonic::LdcW,
            0x14 => Mnemonic::Ldc2W,
            0x6d => Mnemonic::Ldiv,
            0x16 => Mnemonic::Lload,
            0x1e => Mnemonic::Lload0,
            0x1f => Mnemonic::Lload1,
            0x20 => Mnemonic::Lload2,
            0x21 => Mnemonic::Lload3,
            0x69 => Mnemonic::Lmul,
            0x75 => Mnemonic::Lneg,
            0xab => Mnemonic::Lookupswitch,
            0x81 => Mnemonic::Lor,
            0x71 => Mnemonic::Lrem,
            0xad => Mnemonic::Lreturn,
            0x79 => Mnemonic::Lshl,
            0x7b => Mnemonic::Lshr,
            0x37 => Mnemonic::Lstore,
            0x3f => Mnemonic::Lstore0,
            0x40 => Mnemonic::Lstore1,
            0x41 => Mnemonic::Lstore2,
            0x42 => Mnemonic::Lstore3,
            0x65 => Mnemonic::Lsub,
            0x7d => Mnemonic::Lushr,
            0x83 => Mnemonic::Lxor,
            0xc2 => Mnemonic::Monitorenter,
            0xc3 => Mnemonic::Monitorexit,
            0xc5 => Mnemonic::Multianewarray,
            0xbb => Mnemonic::New,
            0xbc => Mnemonic::Newarray,
            0x00 => Mnemonic::Nop,
            0x57 => Mnemonic::Pop,
            0x58 => Mnemonic::Pop2,
            0xb5 => Mnemonic::Putfield,
            0xb3 => Mnemonic::Putstatic,
            0xa9 => Mnemonic::Ret,
            0xb1 => Mnemonic::Return,
            0x35 => Mnemonic::Saload,
            0x56 => Mnemonic::Satore,
            0x11 => Mnemonic::Sipush,
            0x5f => Mnemonic::Swap,
            0xaa => Mnemonic::Tableswitch,
            0xc4 => Mnemonic::WideOp,
            0xc4 => Mnemonic::WideIinc,
            _ => Mnemonic::Unknown(value),
        }
    }
}
