mod instructions;

enum Mnemomic {
    Aaload,
    Aastore,
    AconstNull,
    Aload,
    Aload0,
    Aload1,
    Aload2,
    Aload3,
    Anewarray,
    Areturn,
    Arraylength,
    Astore,
    Astore0,
    Astore1,
    Astore2,
    Astore3,
    Athrow,
    Baload,
    Bastore,
    Bipush,
    Caload,
    Castore,
    Checkcast,
    D2f,
    D2i,
    D2l,
    Dadd,
    Daload,
    Dastore,
    Dcmpg,
    Dcmpl,
    Dconst0,
    Dconst1,
    Ddiv,
    Dload,
    Dload0,
    Dload1,
    Dload2,
    Dload3,
    Dmul,
    Dneg,
    Drem,
    Dreturn,
    Dstore,
    Dstore0,
    Dstore1,
    Dstore2,
    Dstore3,
    Dsub,
    Dup,
    DupX1,
    DupX2,
    Dup2,
    Dup2X1,
    Dup2X2,
    F2d,
    F2i,
    F2l,
    Fadd,
    Faload,
    Fastore,
    Fcmpg,
    Fcmpl,
    Fconst0,
    Fconst1,
    Fconst2,
    Fdiv,
    Fload,
    Fload0,
    Fload1,
    Fload2,
    Fload3,
    Fmul,
    Fneg,
    Frem,
    Freturn,
    Fstore,
    Fstore0,
    Fstore1,
    Fstore2,
    Fstore3,
    Fsub,
    Getfield,
    Getstatic,
    Goto,
    GotoW,
    I2b,
    I2c,
    I2d,
    I2f,
    I2l,
    I2s,
    Iadd,
    Iaload,
    Iand,
    Iastore,
    IconstM1,
    Iconst0,
    Iconst1,
    Iconst2,
    Iconst3,
    Iconst4,
    Iconst5,
    Idiv,
    IfAcmpeq,
    IfAcmpne,
    Ifeq,
    Ifne,
    Iflt,
    Ifge,
    Ifgt,
    Ifle,
    Ifnonnull,
    Ifnull,
    Iinc,
    Iload,
    Iload0,
    Iload1,
    Iload2,
    Iload3,
    Imul,
    Ineg,
    Instanceof,
    Invokedynamic,
    Invokeinterface,
    Invokespecial,
    Invokestatic,
    Invokevirtual,
    Ior,
    Irem,
    Ireturn,
    Ishl,
    Ishr,
    Istore,
    Istore0,
    Istore1,
    Istore2,
    Istore3,
    Isub,
    Iushr,
    Ixor,
    Jsr,
    JsrW,
    L2d,
    L2f,
    L2i,
    Ladd,
    Laload,
    Land,
    Lastore,
    Lcmp,
    Lconst0,
    Lconst1,
    Ldc,
    LdcW,
    Ldc2W,
    Ldiv,
    Lload,
    Lload0,
    Lload1,
    Lload2,
    Lload3,
    Lmul,
    Lneg,
    Lookupswitch,
    Lor,
    Lrem,
    Lreturn,
    Lshl,
    Lshr,
    Lstore,
    Lstore0,
    Lstore1,
    Lstore2,
    Lstore3,
    Lsub,
    Lushr,
    Lxor,
    Monitorenter,
    Monitorexit,
    Multianewarray,
    New,
    Newarray,
    Nop,
    Pop,
    Pop2,
    Putfield,
    Putstatic,
    Ret,
    Return,
    Saload,
    Satore,
    Sipush,
    Swap,
    Tableswitch,
    Wide,
}

impl From<Mnemomic> for String {
    fn from(value: Mnemomic) -> Self {
        match value {
            Mnemomic::Aaload => "aaload",
            Mnemomic::Aastore => "aastore",
            Mnemomic::AconstNull => "aconst_null",
            Mnemomic::Aload => "aload",
            Mnemomic::Aload0 => "aload_0",
            Mnemomic::Aload1 => "aload_1",
            Mnemomic::Aload2 => "aload_2",
            Mnemomic::Aload3 => "aload_3",
            Mnemomic::Anewarray => "anewarray",
            Mnemomic::Areturn => "areturn",
            Mnemomic::Arraylength => "arraylength",
            Mnemomic::Astore => "astore",
            Mnemomic::Astore0 => "astore_0",
            Mnemomic::Astore1 => "astore_1",
            Mnemomic::Astore2 => "astore_2",
            Mnemomic::Astore3 => "astore_3",
            Mnemomic::Athrow => "athrow",
            Mnemomic::Baload => "baload",
            Mnemomic::Bastore => "bastore",
            Mnemomic::Bipush => "bipush",
            Mnemomic::Caload => "caload",
            Mnemomic::Castore => "castore",
            Mnemomic::Checkcast => "checkcast",
            Mnemomic::D2f => "d2f",
            Mnemomic::D2i => "d2i",
            Mnemomic::D2l => "d2l",
            Mnemomic::Dadd => "dadd",
            Mnemomic::Daload => "daload",
            Mnemomic::Dastore => "dastore",
            Mnemomic::Dcmpg => "dcmpg",
            Mnemomic::Dcmpl => "dcmpl",
            Mnemomic::Dconst0 => "dconst_0",
            Mnemomic::Dconst1 => "dconst_1",
            Mnemomic::Ddiv => "ddiv",
            Mnemomic::Dload => "dload",
            Mnemomic::Dload0 => "dload_0",
            Mnemomic::Dload1 => "dload_1",
            Mnemomic::Dload2 => "dload_2",
            Mnemomic::Dload3 => "dload_3",
            Mnemomic::Dmul => "dmul",
            Mnemomic::Dneg => "dneg",
            Mnemomic::Drem => "drem",
            Mnemomic::Dreturn => "dreturn",
            Mnemomic::Dstore => "dstore",
            Mnemomic::Dstore0 => "dstore_0",
            Mnemomic::Dstore1 => "dstore_1",
            Mnemomic::Dstore2 => "dstore_2",
            Mnemomic::Dstore3 => "dstore_3",
            Mnemomic::Dsub => "dsub",
            Mnemomic::Dup => "dup",
            Mnemomic::DupX1 => "dup_x1",
            Mnemomic::DupX2 => "dup_x2",
            Mnemomic::Dup2 => "dup2",
            Mnemomic::Dup2X1 => "dup2_x1",
            Mnemomic::Dup2X2 => "dup2_x2",
            Mnemomic::F2d => "f2d",
            Mnemomic::F2i => "f2i",
            Mnemomic::F2l => "f2l",
            Mnemomic::Fadd => "fadd",
            Mnemomic::Faload => "faload",
            Mnemomic::Fastore => "fastore",
            Mnemomic::Fcmpg => "fcmpg",
            Mnemomic::Fcmpl => "fcmpl",
            Mnemomic::Fconst0 => "fconst_0",
            Mnemomic::Fconst1 => "fconst_1",
            Mnemomic::Fconst2 => "fconst_2",
            Mnemomic::Fdiv => "fdiv",
            Mnemomic::Fload => "fload",
            Mnemomic::Fload0 => "fload_0",
            Mnemomic::Fload1 => "fload_1",
            Mnemomic::Fload2 => "fload_2",
            Mnemomic::Fload3 => "fload_3",
            Mnemomic::Fmul => "fmul",
            Mnemomic::Fneg => "fneg",
            Mnemomic::Frem => "frem",
            Mnemomic::Freturn => "freturn",
            Mnemomic::Fstore => "fstore",
            Mnemomic::Fstore0 => "fstore_0",
            Mnemomic::Fstore1 => "fstore_1",
            Mnemomic::Fstore2 => "fstore_2",
            Mnemomic::Fstore3 => "fstore_3",
            Mnemomic::Fsub => "fsub",
            Mnemomic::Getfield => "getfield",
            Mnemomic::Getstatic => "getstatic",
            Mnemomic::Goto => "goto",
            Mnemomic::GotoW => "goto_w",
            Mnemomic::I2b => "i2b",
            Mnemomic::I2c => "i2c",
            Mnemomic::I2d => "i2d",
            Mnemomic::I2f => "i2f",
            Mnemomic::I2l => "i2l",
            Mnemomic::I2s => "i2s",
            Mnemomic::Iadd => "iadd",
            Mnemomic::Iaload => "iaload",
            Mnemomic::Iand => "iand",
            Mnemomic::Iastore => "iastore",
            Mnemomic::IconstM1 => "iconst_m1",
            Mnemomic::Iconst0 => "iconst_0",
            Mnemomic::Iconst1 => "iconst_1",
            Mnemomic::Iconst2 => "iconst_2",
            Mnemomic::Iconst3 => "iconst_3",
            Mnemomic::Iconst4 => "iconst_4",
            Mnemomic::Iconst5 => "iconst_5",
            Mnemomic::Idiv => "idiv",
            Mnemomic::IfAcmpeq => "if_acmpeq",
            Mnemomic::IfAcmpne => "if_acmpne",
            Mnemomic::Ifeq => "ifeq",
            Mnemomic::Ifne => "ifne",
            Mnemomic::Iflt => "iflt",
            Mnemomic::Ifge => "ifge",
            Mnemomic::Ifgt => "ifgt",
            Mnemomic::Ifle => "ifle",
            Mnemomic::Ifnonnull => "ifnonnull",
            Mnemomic::Ifnull => "ifnull",
            Mnemomic::Iinc => "iinc",
            Mnemomic::Iload => "iload",
            Mnemomic::Iload0 => "iload_0",
            Mnemomic::Iload1 => "iload_1",
            Mnemomic::Iload2 => "iload_2",
            Mnemomic::Iload3 => "iload_3",
            Mnemomic::Imul => "imul",
            Mnemomic::Ineg => "ineg",
            Mnemomic::Instanceof => "instanceof",
            Mnemomic::Invokedynamic => "invokedynamic",
            Mnemomic::Invokeinterface => "invokeinterface",
            Mnemomic::Invokespecial => "invokespecial",
            Mnemomic::Invokestatic => "invokestatic",
            Mnemomic::Invokevirtual => "invokevirtual",
            Mnemomic::Ior => "ior",
            Mnemomic::Irem => "irem",
            Mnemomic::Ireturn => "ireturn",
            Mnemomic::Ishl => "ishl",
            Mnemomic::Ishr => "ishr",
            Mnemomic::Istore => "istore",
            Mnemomic::Istore0 => "istore_0",
            Mnemomic::Istore1 => "istore_1",
            Mnemomic::Istore2 => "istore_2",
            Mnemomic::Istore3 => "istore_3",
            Mnemomic::Isub => "isub",
            Mnemomic::Iushr => "iushr",
            Mnemomic::Ixor => "ixor",
            Mnemomic::Jsr => "jsr",
            Mnemomic::JsrW => "jsr_w",
            Mnemomic::L2d => "l2d",
            Mnemomic::L2f => "l2f",
            Mnemomic::L2i => "l2i",
            Mnemomic::Ladd => "ladd",
            Mnemomic::Laload => "laload",
            Mnemomic::Land => "land",
            Mnemomic::Lastore => "lastore",
            Mnemomic::Lcmp => "lcmp",
            Mnemomic::Lconst0 => "lconst_0",
            Mnemomic::Lconst1 => "lconst_1",
            Mnemomic::Ldc => "ldc",
            Mnemomic::LdcW => "ldc_w",
            Mnemomic::Ldc2W => "ldc2_w",
            Mnemomic::Ldiv => "ldiv",
            Mnemomic::Lload => "lload",
            Mnemomic::Lload0 => "lload_0",
            Mnemomic::Lload1 => "lload_1",
            Mnemomic::Lload2 => "lload_2",
            Mnemomic::Lload3 => "lload_3",
            Mnemomic::Lmul => "lmul",
            Mnemomic::Lneg => "lneg",
            Mnemomic::Lookupswitch => "lookupswitch",
            Mnemomic::Lor => "lor",
            Mnemomic::Lrem => "lrem",
            Mnemomic::Lreturn => "lreturn",
            Mnemomic::Lshl => "lshl",
            Mnemomic::Lshr => "lshr",
            Mnemomic::Lstore => "lstore",
            Mnemomic::Lstore0 => "lstore_0",
            Mnemomic::Lstore1 => "lstore_1",
            Mnemomic::Lstore2 => "lstore_2",
            Mnemomic::Lstore3 => "lstore_3",
            Mnemomic::Lsub => "lsub",
            Mnemomic::Lushr => "lushr",
            Mnemomic::Lxor => "lxor",
            Mnemomic::Monitorenter => "monitorenter",
            Mnemomic::Monitorexit => "monitorexit",
            Mnemomic::Multianewarray => "multianewarray",
            Mnemomic::New => "new",
            Mnemomic::Newarray => "newarray",
            Mnemomic::Nop => "nop",
            Mnemomic::Pop => "pop",
            Mnemomic::Pop2 => "pop2",
            Mnemomic::Putfield => "putfield",
            Mnemomic::Putstatic => "putstatic",
            Mnemomic::Ret => "ret",
            Mnemomic::Return => "return",
            Mnemomic::Saload => "saload",
            Mnemomic::Satore => "satore",
            Mnemomic::Sipush => "sipush",
            Mnemomic::Swap => "swap",
            Mnemomic::Tableswitch => "tableswitch",
            Mnemomic::Wide => "wide",
        }
        .into()
    }
}

impl From<Mnemomic> for u8 {
    fn from(value: Mnemomic) -> Self {
        match value {
            Mnemomic::Aaload => todo!(),
            Mnemomic::Aastore => todo!(),
            Mnemomic::AconstNull => todo!(),
            Mnemomic::Aload => todo!(),
            Mnemomic::Aload0 => todo!(),
            Mnemomic::Aload1 => todo!(),
            Mnemomic::Aload2 => todo!(),
            Mnemomic::Aload3 => todo!(),
            Mnemomic::Anewarray => todo!(),
            Mnemomic::Areturn => todo!(),
            Mnemomic::Arraylength => todo!(),
            Mnemomic::Astore => todo!(),
            Mnemomic::Astore0 => todo!(),
            Mnemomic::Astore1 => todo!(),
            Mnemomic::Astore2 => todo!(),
            Mnemomic::Astore3 => todo!(),
            Mnemomic::Athrow => todo!(),
            Mnemomic::Baload => todo!(),
            Mnemomic::Bastore => todo!(),
            Mnemomic::Bipush => todo!(),
            Mnemomic::Caload => todo!(),
            Mnemomic::Castore => todo!(),
            Mnemomic::Checkcast => todo!(),
            Mnemomic::D2f => todo!(),
            Mnemomic::D2i => todo!(),
            Mnemomic::D2l => todo!(),
            Mnemomic::Dadd => todo!(),
            Mnemomic::Daload => todo!(),
            Mnemomic::Dastore => todo!(),
            Mnemomic::Dcmpg => todo!(),
            Mnemomic::Dcmpl => todo!(),
            Mnemomic::Dconst0 => todo!(),
            Mnemomic::Dconst1 => todo!(),
            Mnemomic::Ddiv => todo!(),
            Mnemomic::Dload => todo!(),
            Mnemomic::Dload0 => todo!(),
            Mnemomic::Dload1 => todo!(),
            Mnemomic::Dload2 => todo!(),
            Mnemomic::Dload3 => todo!(),
            Mnemomic::Dmul => todo!(),
            Mnemomic::Dneg => todo!(),
            Mnemomic::Drem => todo!(),
            Mnemomic::Dreturn => todo!(),
            Mnemomic::Dstore => todo!(),
            Mnemomic::Dstore0 => todo!(),
            Mnemomic::Dstore1 => todo!(),
            Mnemomic::Dstore2 => todo!(),
            Mnemomic::Dstore3 => todo!(),
            Mnemomic::Dsub => todo!(),
            Mnemomic::Dup => todo!(),
            Mnemomic::DupX1 => todo!(),
            Mnemomic::DupX2 => todo!(),
            Mnemomic::Dup2 => todo!(),
            Mnemomic::Dup2X1 => todo!(),
            Mnemomic::Dup2X2 => todo!(),
            Mnemomic::F2d => todo!(),
            Mnemomic::F2i => todo!(),
            Mnemomic::F2l => todo!(),
            Mnemomic::Fadd => todo!(),
            Mnemomic::Faload => todo!(),
            Mnemomic::Fastore => todo!(),
            Mnemomic::Fcmpg => todo!(),
            Mnemomic::Fcmpl => todo!(),
            Mnemomic::Fconst0 => todo!(),
            Mnemomic::Fconst1 => todo!(),
            Mnemomic::Fconst2 => todo!(),
            Mnemomic::Fdiv => todo!(),
            Mnemomic::Fload => todo!(),
            Mnemomic::Fload0 => todo!(),
            Mnemomic::Fload1 => todo!(),
            Mnemomic::Fload2 => todo!(),
            Mnemomic::Fload3 => todo!(),
            Mnemomic::Fmul => todo!(),
            Mnemomic::Fneg => todo!(),
            Mnemomic::Frem => todo!(),
            Mnemomic::Freturn => todo!(),
            Mnemomic::Fstore => todo!(),
            Mnemomic::Fstore0 => todo!(),
            Mnemomic::Fstore1 => todo!(),
            Mnemomic::Fstore2 => todo!(),
            Mnemomic::Fstore3 => todo!(),
            Mnemomic::Fsub => todo!(),
            Mnemomic::Getfield => todo!(),
            Mnemomic::Getstatic => todo!(),
            Mnemomic::Goto => todo!(),
            Mnemomic::GotoW => todo!(),
            Mnemomic::I2b => todo!(),
            Mnemomic::I2c => todo!(),
            Mnemomic::I2d => todo!(),
            Mnemomic::I2f => todo!(),
            Mnemomic::I2l => todo!(),
            Mnemomic::I2s => todo!(),
            Mnemomic::Iadd => todo!(),
            Mnemomic::Iaload => todo!(),
            Mnemomic::Iand => todo!(),
            Mnemomic::Iastore => todo!(),
            Mnemomic::IconstM1 => todo!(),
            Mnemomic::Iconst0 => todo!(),
            Mnemomic::Iconst1 => todo!(),
            Mnemomic::Iconst2 => todo!(),
            Mnemomic::Iconst3 => todo!(),
            Mnemomic::Iconst4 => todo!(),
            Mnemomic::Iconst5 => todo!(),
            Mnemomic::Idiv => todo!(),
            Mnemomic::IfAcmpeq => todo!(),
            Mnemomic::IfAcmpne => todo!(),
            Mnemomic::Ifeq => todo!(),
            Mnemomic::Ifne => todo!(),
            Mnemomic::Iflt => todo!(),
            Mnemomic::Ifge => todo!(),
            Mnemomic::Ifgt => todo!(),
            Mnemomic::Ifle => todo!(),
            Mnemomic::Ifnonnull => todo!(),
            Mnemomic::Ifnull => todo!(),
            Mnemomic::Iinc => todo!(),
            Mnemomic::Iload => todo!(),
            Mnemomic::Iload0 => todo!(),
            Mnemomic::Iload1 => todo!(),
            Mnemomic::Iload2 => todo!(),
            Mnemomic::Iload3 => todo!(),
            Mnemomic::Imul => todo!(),
            Mnemomic::Ineg => todo!(),
            Mnemomic::Instanceof => todo!(),
            Mnemomic::Invokedynamic => todo!(),
            Mnemomic::Invokeinterface => todo!(),
            Mnemomic::Invokespecial => todo!(),
            Mnemomic::Invokestatic => todo!(),
            Mnemomic::Invokevirtual => todo!(),
            Mnemomic::Ior => todo!(),
            Mnemomic::Irem => todo!(),
            Mnemomic::Ireturn => todo!(),
            Mnemomic::Ishl => todo!(),
            Mnemomic::Ishr => todo!(),
            Mnemomic::Istore => todo!(),
            Mnemomic::Istore0 => todo!(),
            Mnemomic::Istore1 => todo!(),
            Mnemomic::Istore2 => todo!(),
            Mnemomic::Istore3 => todo!(),
            Mnemomic::Isub => todo!(),
            Mnemomic::Iushr => todo!(),
            Mnemomic::Ixor => todo!(),
            Mnemomic::Jsr => todo!(),
            Mnemomic::JsrW => todo!(),
            Mnemomic::L2d => todo!(),
            Mnemomic::L2f => todo!(),
            Mnemomic::L2i => todo!(),
            Mnemomic::Ladd => todo!(),
            Mnemomic::Laload => todo!(),
            Mnemomic::Land => todo!(),
            Mnemomic::Lastore => todo!(),
            Mnemomic::Lcmp => todo!(),
            Mnemomic::Lconst0 => todo!(),
            Mnemomic::Lconst1 => todo!(),
            Mnemomic::Ldc => todo!(),
            Mnemomic::LdcW => todo!(),
            Mnemomic::Ldc2W => todo!(),
            Mnemomic::Ldiv => todo!(),
            Mnemomic::Lload => todo!(),
            Mnemomic::Lload0 => todo!(),
            Mnemomic::Lload1 => todo!(),
            Mnemomic::Lload2 => todo!(),
            Mnemomic::Lload3 => todo!(),
            Mnemomic::Lmul => todo!(),
            Mnemomic::Lneg => todo!(),
            Mnemomic::Lookupswitch => todo!(),
            Mnemomic::Lor => todo!(),
            Mnemomic::Lrem => todo!(),
            Mnemomic::Lreturn => todo!(),
            Mnemomic::Lshl => todo!(),
            Mnemomic::Lshr => todo!(),
            Mnemomic::Lstore => todo!(),
            Mnemomic::Lstore0 => todo!(),
            Mnemomic::Lstore1 => todo!(),
            Mnemomic::Lstore2 => todo!(),
            Mnemomic::Lstore3 => todo!(),
            Mnemomic::Lsub => todo!(),
            Mnemomic::Lushr => todo!(),
            Mnemomic::Lxor => todo!(),
            Mnemomic::Monitorenter => todo!(),
            Mnemomic::Monitorexit => todo!(),
            Mnemomic::Multianewarray => todo!(),
            Mnemomic::New => todo!(),
            Mnemomic::Newarray => todo!(),
            Mnemomic::Nop => todo!(),
            Mnemomic::Pop => todo!(),
            Mnemomic::Pop2 => todo!(),
            Mnemomic::Putfield => todo!(),
            Mnemomic::Putstatic => todo!(),
            Mnemomic::Ret => todo!(),
            Mnemomic::Return => todo!(),
            Mnemomic::Saload => todo!(),
            Mnemomic::Satore => todo!(),
            Mnemomic::Sipush => todo!(),
            Mnemomic::Swap => todo!(),
            Mnemomic::Tableswitch => todo!(),
            Mnemomic::Wide => todo!(),
        }
    }
}
